site_name: mkdocs-pdf-export-plugin
site_description: Project documentation using Mkdocs
site_url: https://kartoza.com/en/
site_author: Kartoza
theme:
  name: material
use_directory_urls: false
plugins:
  - search
  - pdf-export:
      combined: true
      theme_handler_path: theme-handler/cinder.py
extra_css:
    - assets/extra.css
    - assets/second_extra.css
nav:
  - Intro: index.md
  - Options: options.md

repo_url: https://github.com/zhaoterryy/mkdocs-pdf-export-plugin
edit_uri: edit/master/docs/
remote_name: git@github.com:zhaoterryy/mkdocs-pdf-export-plugin.git
